
version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      # Override Supabase connection parameters here if needed
      # - SUPABASE_URL=your-supabase-url
      # - SUPABASE_ANON_KEY=your-supabase-anon-key
