// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwhkckwtfsvuduucdfyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aGtja3d0ZnN2dWR1dWNkZnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjY3NzIsImV4cCI6MjA2MDIwMjc3Mn0.Eas8rs5Z1oOonuOTiDG-sHm_l3kVZpgDUzC1ykB9lLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);