
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getDatabaseConfig } from '@/config/database';

// Get configuration from the config file, which can be overridden by environment variables
const { supabaseUrl, supabaseAnonKey } = getDatabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
