// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxplnqouwsvwsoxgkwgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cGxucW91d3N2d3NveGdrd2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDEzMTQsImV4cCI6MjA2MDQxNzMxNH0.nvN-qYm_JdmRgAvD2apaOeuwFRhXLM5OOjKfSg2PwmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);